apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 22.2.3
    helm:
      values: |
        service:
          type: NodePort
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-test
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  
